version: '3'

services:
    mysql-db:
        image: mysql:latest
        container_name: mysql-db
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_ROOT_HOST=%
